---
title: "Telerilevamento per l'agricoltura di precisione"
output: 
 flexdashboard::flex_dashboard:
    theme: united
    social: menu
   # logo: C:/Users/croci/OneDrive/Desktop/Immagine1_positive.png
    orientation: columns
    # source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(ggplot2)
library(mgcv)

library("shiny")
library("shinythemes")
library('plotly')


```

PROSAIL Model
=====================================

Inputs {.sidebar}
-----------------------------------------------------------------------
#### Parametri fogliari
```{r}
# sliderInput('sampleSize', 'Sample Size', min=1, max=nrow(dataset), value=min(1000, nrow(dataset)), step=500, round=0)

# checkboxInput('jitter', 'Jitter', value = TRUE)
# checkboxInput('smooth', 'Smooth', value = TRUE)
sliderInput("N", label = "Spessore mesofillo fogliare", min = 1, value = c(1.2,1.5), max = 2.5, step = .1, animate = animationOptions(interval = 1000, loop = T))
sliderInput("Cm", label = "Sostanza secca fogliare (Cm)",  min = 0, value = c(0.01,0.012), max = 0.02, step = .001 )
sliderInput("Cw", label = "Contenuto d'acqua (Cw)", min = 0, value = c(0.02, 0.03), max = 0.05 , step = .01 )
sliderInput("Cab", label = "Contenuto di clorofilla fogliare (Cab)", min = 0, value = c(45,60) , max = 90,  step = 5, animate = animationOptions(interval = 1000, loop = T))
# sliderInput("Car", label = "Carotenoid content", min = 0, value = c(8,12), max = 20)
#Cw_Rel <- seq(0.75,0.9, .05)


```

#### Parametri della canopy
```{r}
sliderInput( "LAI", label = "Indice di area fogliare (LAI) (m\u00b2 / m\u00b2)",
                                  min = 1, max = 10, step = .5,
                                  value =  c(1, 2),
                                  animate = animationOptions(interval = 1000, loop = T))
sliderInput("lidfa", label = "Angolo fogliare (ALA °)",  min = 0, value = c(45,67), max = 90, step = .5)
# sliderInput("hspt", label = "Hotspot parameter (hspot)", min = .01, value = .05, max = .5, step = .02)
```

##### Satellite
```{r}
selectInput("sensor", label = "Scegliere sensore: ",
choices = c("Landsat4","Landsat5","Landsat7","Landsat8","Quickbird","RapidEye","Sentinel2a","WorldView2-4","WorldView2-8"), selected = "Sentinel2a")
```


Outputs
-----------------------------------------------------------------------

### Riflettanza fogliare - PROSPECT
```{r}
dataset <- reactive({
  # diamonds[sample(nrow(diamonds), input$sampleSize),]
 spectra <- hsdar::PROSPECT(parameterList = expand.grid(N= input$N, Cm =input$Cm, Cw=input$Cw, Cab =input$Cab#, #Car =input$Car,
                                                        ));
  prospectfile <- data.frame( Wav = 400:2500, Reflectance = t(spectra@spectra@spectra_ma) )
  Reflectance = apply(prospectfile[, 2:ncol(prospectfile)], 1, mean)
  Reflectance.sd = apply(prospectfile[, 2:ncol(prospectfile)], 1, sd)
        data.frame(Wav = 400:2500, Reflectance = Reflectance, Reflectance.sd = Reflectance.sd)
        })

renderPlotly({
  p1 <- ggplot(dataset(),aes(x=Wav,y=Reflectance)) + geom_line(colour='darkgreen', lty="dashed", lwd=1.2) +
            geom_ribbon(aes(ymin=Reflectance-Reflectance.sd, ymax=Reflectance+Reflectance.sd, x=Wav), alpha = 0.3,  fill="green") +
            theme_classic(base_size = 14) +
            labs(x="Wavelength (nm)", y = "Reflectance (-)") +
            scale_x_continuous(limits = c(400, 2500)) + scale_y_continuous(limits = c(0, 1))
  
 ggplotly(p1)
})
```

### Riflettanza della canopy - SAIL
```{r}

dataset2 <- reactive({
  # diamonds[sample(nrow(diamonds), input$sampleSize),]
spectra <- hsdar::PROSAIL(parameterList = expand.grid(
            N= input$N, Cm =input$Cm, Cw=input$Cw, Cab =input$Cab, # Car =input$Car,
            LAI=input$LAI, 
            TypeLidf = 2, 
            lidfa=input$lidfa #,hspot=input$hspt,tts=input$tts,tto=input$tto,psi=input$psi
            )
        );
prosailfile.all <- data.frame( Wav = 400:2500, Reflectance = t(spectra@spectra@spectra_ma) )
prosailfile <- data.frame( Wav = 400:2500, Reflectance = t(spectra@spectra@spectra_ma) )
Reflectance <- apply(prosailfile[, 2:ncol(prosailfile)], 1, mean)
Reflectance.sd <- apply(prosailfile[, 2:ncol(prosailfile)], 1, sd)
        data.frame(Wav = 400:2500, Reflectance = Reflectance, Reflectance.sd =Reflectance.sd)

        })


   dataset_s2 <- reactive({
      spectra <- hsdar::PROSAIL(parameterList = expand.grid(
            N= input$N, Cm =input$Cm, Cw=input$Cw, Cab =input$Cab, #Car =input$Car,
            LAI=input$LAI, 
            TypeLidf = 2, 
            lidfa=input$lidfa #,hspot=input$hspt,tts=input$tts,tto=input$tto,psi=input$psi
            )
        );
     spectra.S2 <- hsdar::spectralResampling(spectra, input$sensor)
        prosail.spectra.S2 <- spectra.S2@spectra@spectra_ma
        
        Reflectance.s2 = apply(prosail.spectra.S2[, 1:ncol(prosail.spectra.S2)], 2, mean)
        Reflectance.s2.sd = apply(prosail.spectra.S2[, 1:ncol(prosail.spectra.S2)], 2, sd)
        
        data.frame(Wav = spectra.S2@wavelength, Reflectance = Reflectance.s2, Reflectance.sd =Reflectance.s2.sd)
        
  })
   
renderPlotly({ 
p <- ggplot() +
            geom_line(data = dataset2(), aes(x=Wav,y=Reflectance),colour='darkred', lty="dashed", lwd=1.2) +
            geom_ribbon(data = dataset2(), aes(ymin=Reflectance-Reflectance.sd, ymax=Reflectance+Reflectance.sd, x=Wav), fill="red", alpha = 0.3) +
            #  geom_errorbar(data=prosailfile.s2, mapping=aes(x=Wav, ymin=Reflectance-Reflectance.sd, ymax=Reflectance+Reflectance.sd), width=0.2, size=1, color="blue") + 
                        geom_point(data = dataset_s2(), aes(x = Wav, y = Reflectance), fill="green", color = "black",  pch=21, size=2, alpha=.33) +
            theme_classic(base_size = 14) +
            labs(x="Wavelength (nm)", y = "Reflectance (-)") +
            scale_x_continuous(limits = c(400, 2500)) + scale_y_continuous(limits = c(0, 1))

      ggplotly(p)
     })
```


Info
=====================================
Created by: UCSC Field Crops Group - Remote sensing team
**Michele Croci**